### ISSUE TITLE
First reaction still has wrong border-radius

### ISSUE THREAD

**Issue by Kir-Antipov** [Kir-Antipov/GitHub-Defreshed#20]
![radius](https://user-images.githubusercontent.com/40232067/89736798-cb4b6980-da74-11ea-8cd8-f7b6b26fb70d.png)

Problem rule:
```css
.comment-reactions-options .reaction-summary-item:first-child {
    border-bottom-left-radius: 6px;
}
```

**Comment by Kir-Antipov** [comment]
Also, Microsoft somehow hecked up with the line height, which caused a small distance between the upper border of the reaction and the container.

Problem rule:
```css
.reaction-summary-item {
    line-height: 18px;
}
```

Can be fixed with:
```css
.reaction-summary-item {
    line-height: 1.3;
}
```
